name: tests

on: [ push, pull_request ]

jobs:
  ubuntu:
    name: Ubuntu PHP ${{ matrix.php-versions }}) ${{ matrix.type }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [ 5.6, 7.1, 7.2, 7.4, 8.0, 8.1, 8.2 ]
        type: [ cli, fpm ]
    steps:
      # 1- Checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 10000
      # 2- Setup PHP
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      # 3- Setup xdebug
      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug
      # 4- Setup xdebug
      - name: Setup PHP-SPX
        run: sudo ./install.sh ${{ matrix.php-version }} ${{ matrix.type }}
